on:
  push:
    branches:
      - master
    paths:
      - 'packages/docs/*'

      
jobs:
  build-and-deploy-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install documentation dependencies
      run: npm run setup
    - name: Build documentation website
      run: npm run build-docs
    - name: Commit new website build
      run: |
        git config --global user.name 'ArsalaBangash'
        git config --global user.email 'arsalabangash@gmail.com'
        git commit -am "Deploying new website build"
        git push